### ISSUE TITLE
set up Vue router

### ISSUE THREAD

**Issue by AntonTymczenko** [chingu-voyage4/Bears-Team-15#10]
/ = Homepage
/home = Homepage>Dashboard
/lesson = Lesson
/collection = Collection

connected to #18

**Comment by tomski80** [comment]
I think routes "/" and "/home" should point to the same component - Homepage. If you want use nested routes for dashboard for some reason (I don't see the need for it). then route should be for it '/dashboard' or '/home/dashboard'.
