### ISSUE TITLE
fix footer

### ISSUE THREAD

**Issue by svmi3195** [chingu-voyage4/Bears-Team-15#31]
In Chrome: when you shrink the page to smaller size, footer doesn't go off the viewport and is on top of the main content. This doesn't happen in Firefox.
[image (first in Chrome, second in Firefox)](https://files.slack.com/files-pri/T95JN6KRA-F9DMQ9HJM/footer.png)

**Comment by AntonTymczenko** [comment]
was resolved by commit cdc9114d09e54622b365ca3c58f6c6be8ef8a845
