### ISSUE TITLE
TypeError: _vm.collection is undefined

### ISSUE THREAD

**Issue by svmi3195** [chingu-voyage4/Bears-Team-15#75]
If I go to add new collection view and then refresh, it doesn't render anymore and this error log appears:

> [Vue warn]: Error in render: "TypeError: _vm.collection is undefined"
> found in
> ---> <Collection> at src\components\Collection.vue
>        <Homepage> at src\components\Homepage.vue
>          <App> at src\App.vue
>            <Root>

**Comment by AntonTymczenko** [comment]
yes, it is very strange. and it is definitely not a problem of CollectionEdit component or even CollectionNew component. It's something in the routing... because this particular view (`/collection/new`) shouldn't have  inside itself this `src\components\Collection.vue` at all

**Comment by AntonTymczenko** [comment]
so) just after I've verbalized the thesis above, I've realized that router regards `/new` in path as an `/:id`, so I just put `path: '/collection/new'` before `path: '/collection/:id'` and – boom! – no problem :)
